/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Administrador;

import Menu.MenuAdministrador;
import Menu.MenuProveedor;
import Menu.MenuVendedor;
import Menu.Menu_Ventana;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    
    // clases
    LoginClass logObj = new LoginClass();
    
    public VentanaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnLog = new javax.swing.JButton();
        txtErrorMsg = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        showPassbtn = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel1.setText("INICIAR SESIÓN");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Usuario: ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña: ");

        txtUser.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N

        btnLog.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        btnLog.setText("Ingresar");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        txtErrorMsg.setVisible(false);
        txtErrorMsg.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txtErrorMsg.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorMsg.setText("Error , vuelva a digitar la contraseña");

        passwordField.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        showPassbtn.setBackground(new java.awt.Color(51, 102, 255));
        showPassbtn.setText("Mostrar contraseña");
        showPassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(btnLog)
                .addGap(206, 206, 206))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtErrorMsg)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showPassbtn))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(passwordField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtErrorMsg)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPassbtn)
                .addGap(18, 18, 18)
                .addComponent(btnLog)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        // inputs
        String nombreUsuario    = txtUser.getText();
        String password         = passwordField.getText();
        
        // buscando si existe usuario
        boolean verifyUser = logObj.leerArchivoGetUsuario("listaUusuarios.txt", nombreUsuario);
        if (nombreUsuario.equals("") || password.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Rellene todos los campos antes de continuar");
        }
        else
        {
            logObj.leerArchivoIMPRIMIR("listaUusuarios.txt");
            System.out.println("¿ el usuario existe ? " + verifyUser);
            if (verifyUser == true)
            {
                
                int     posicion        = logObj.buscarNombreUsuarioGetPosition("listaUusuarios.txt",nombreUsuario);
                boolean msgPassVerified = logObj.leerArchivoPassword("listaUusuarios.txt", posicion, password);
                
                System.out.println("¿passwrdo correcta? " + msgPassVerified);
                
                if (msgPassVerified == true)
                {
                    System.out.println("contraseña correcta !!! ");
                    txtErrorMsg.setVisible(false); // en caso de que haya tenido un error se resetea 
                    JOptionPane.showMessageDialog(null,"Inicio de sesión correcto !!");
                    String rol = logObj.leerArchivoGetRol(nombreUsuario);
                    // verificar el rol y redirreccionar a la ventana adecuada
                    if ( rol.equals("admin"))
                    {
                        MenuAdministrador adminWindow = new MenuAdministrador("admin");
                        adminWindow.setVisible(true);
                        dispose();
                    }
                    else if ( rol.equals("vendedor"))
                    {
                        MenuVendedor vendedorWindow = new MenuVendedor("vendedor");
                        vendedorWindow.setVisible(true);
                        dispose();
                    }
                    else if ( rol.equals("proveedor"))
                    {
                        MenuProveedor proveedorWindow = new MenuProveedor("proveedor");
                        proveedorWindow.setVisible(true);
                        dispose();
                    }
                    
                }
                else
                {
                    txtErrorMsg.setVisible(true);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "El usuario ingresado no existe");
            }
        }
        
    }//GEN-LAST:event_btnLogActionPerformed

    private void showPassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassbtnActionPerformed
        // TODO add your handling code here:
         if (showPassbtn.isSelected()) 
         {
            passwordField.setEchoChar((char) 0);
            
         } 
         else 
         {
            passwordField.setEchoChar('•');
         }
    }//GEN-LAST:event_showPassbtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JCheckBox showPassbtn;
    private javax.swing.JLabel txtErrorMsg;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
