/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Cliente;


import Menu.MenuAdministrador;
import Menu.MenuVendedor;
import Tests.*;
import Personas.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lorelay
 */
public class Cliente_Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Cliente_Ventana
     */
    
   
    // instancia de la clase Ayuda de package Tests
    Ayudas objAyuda = new Ayudas();
    // instancia de la clase ClienteVector;
    ClienteVector clienteVectores = new ClienteVector();
    // modelo de tabla
    DefaultTableModel   modeloDeTabla       =  new DefaultTableModel();
    DefaultTableModel   modeloDeTablaTel    = new DefaultTableModel();
    DefaultTableModel   modeloDeTablaNombre = new DefaultTableModel();
    
    public String rol = "";
    
    public Cliente_Ventana(String str) 
    {
        initComponents();
        setRol(str);
        modeloDeTabla.addColumn("CODIGO");
        modeloDeTabla.addColumn("DNI");
        modeloDeTabla.addColumn("NOMBRE");
        modeloDeTabla.addColumn("TELEFONO");
        modeloDeTabla.addColumn("COMPRAS TOTALES");
        
        // tabla telgfono
        modeloDeTablaTel.addColumn("CODIGO");
        modeloDeTablaTel.addColumn("TELEFONO");
        
        // tabla nombre
        modeloDeTablaNombre.addColumn("CODIGO");
        modeloDeTablaNombre.addColumn("NOMBRE");
        
        // setting model
        tablaClientes.setModel(modeloDeTabla);
        tablaTelCliente.setModel(modeloDeTablaTel);
        tablaClienteNombres.setModel(modeloDeTablaNombre);
        
        cargarDatosTablaClientes();
        
        //cargarItemsListaCodigo();
    }
    
    public Cliente_Ventana() 
    {
        initComponents();
        modeloDeTabla.addColumn("CODIGO");
        modeloDeTabla.addColumn("DNI");
        modeloDeTabla.addColumn("NOMBRE");
        modeloDeTabla.addColumn("TELEFONO");
        modeloDeTabla.addColumn("COMPRAS TOTALES");
        
        // tabla telgfono
        modeloDeTablaTel.addColumn("CODIGO");
        modeloDeTablaTel.addColumn("TELEFONO");
        
        // tabla nombre
        modeloDeTablaNombre.addColumn("CODIGO");
        modeloDeTablaNombre.addColumn("NOMBRE");
        
        // setting model
        tablaClientes.setModel(modeloDeTabla);
        tablaTelCliente.setModel(modeloDeTablaTel);
        tablaClienteNombres.setModel(modeloDeTablaNombre);
        
        cargarDatosTablaClientes();
        
        //cargarItemsListaCodigo();
    }

    public void setRol(String str)
    {
        rol = str;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        mostratTablaCLientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodeGenrerado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        btnAgregarCliente = new javax.swing.JButton();
        btnGenerarCodigo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listCodTelCliente = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtTelActual = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNuevoTel = new javax.swing.JTextField();
        btnModificarTelefono = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaTelCliente = new javax.swing.JTable();
        tablaClienteTelefono = new javax.swing.JButton();
        btnCargarUploadListaIDModTelCliente = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cboBoxIDEliminar = new javax.swing.JComboBox<>();
        txtDniEliminar = new javax.swing.JTextField();
        txtNombreEliminar = new javax.swing.JTextField();
        txtTelefonoEliminar = new javax.swing.JTextField();
        txtComprasTotalesEliminar = new javax.swing.JTextField();
        btnCargarUploadListaIDEliminarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnModificarNombre = new javax.swing.JButton();
        btnActualizarTabla = new javax.swing.JButton();
        listCodigoCliente = new javax.swing.JComboBox<>();
        txtNombreActual = new javax.swing.JTextField();
        txtNuevoNombre = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaClienteNombres = new javax.swing.JTable();
        btnCargarUploadListaIDModNomCliente = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        mostratTablaCLientes.setText("Mostrar clientes");
        mostratTablaCLientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostratTablaCLientesActionPerformed(evt);
            }
        });

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaClientes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(mostratTablaCLientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(mostratTablaCLientes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MOSTRAR CLIENTES", jPanel3);

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("AGREGAR CLIENTE");

        txtCodeGenrerado.setEditable(false);

        jLabel3.setText("Telefono");

        jLabel4.setText("Nombre");

        jLabel5.setText("DNI");

        btnAgregarCliente.setText("AGREGAR");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        btnGenerarCodigo.setText("Generar Codigo");
        btnGenerarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(121, 121, 121)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodeGenrerado)
                            .addComponent(txtTelefono)
                            .addComponent(txtNombre)
                            .addComponent(txtDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodeGenrerado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarCodigo))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombre)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(489, 489, 489))
        );

        jTabbedPane1.addTab("AGREGAR CLIENTE", jPanel2);

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));

        jLabel7.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MODIFICAR TELEFONO");

        jLabel2.setText("Seleccionar codigo: ");

        listCodTelCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listCodTelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCodTelClienteActionPerformed(evt);
            }
        });

        jLabel11.setText("Telefono Actual");

        txtTelActual.setEditable(false);

        jLabel12.setText("Nuevo Telefono");

        btnModificarTelefono.setText("Modfificar Telfono");
        btnModificarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarTelefonoActionPerformed(evt);
            }
        });

        tablaTelCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tablaTelCliente);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel8);

        tablaClienteTelefono.setText("ActualziarTabla");
        tablaClienteTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaClienteTelefonoActionPerformed(evt);
            }
        });

        btnCargarUploadListaIDModTelCliente.setText("Cargar/Actualizar Lista de Codigo de Cliente");
        btnCargarUploadListaIDModTelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarUploadListaIDModTelClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNuevoTel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnModificarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTelActual, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listCodTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarUploadListaIDModTelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(tablaClienteTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tablaClienteTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnCargarUploadListaIDModTelCliente)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listCodTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuevoTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btnModificarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MODIFICAR TELEFONO", jPanel6);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setForeground(new java.awt.Color(0, 0, 0));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Eliminar Cliente: ");

        jLabel14.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("ID de Cliente : ");

        jLabel15.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("DNI: ");

        jLabel16.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Nombre: ");

        jLabel17.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Telefono:  ");

        jLabel18.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Compras Totales: ");

        cboBoxIDEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboBoxIDEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBoxIDEliminarActionPerformed(evt);
            }
        });

        btnCargarUploadListaIDEliminarCliente.setText("Cargar/Actualizar Lista de ID Cliente");
        btnCargarUploadListaIDEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarUploadListaIDEliminarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setText("Eliminar Cliente");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(326, 326, 326))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCargarUploadListaIDEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cboBoxIDEliminar, 0, 239, Short.MAX_VALUE)
                                        .addComponent(txtDniEliminar)
                                        .addComponent(txtNombreEliminar)
                                        .addComponent(txtTelefonoEliminar)
                                        .addComponent(txtComprasTotalesEliminar)))
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(115, 115, 115))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(btnCargarUploadListaIDEliminarCliente)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cboBoxIDEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDniEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTelefonoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComprasTotalesEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(28, 28, 28)
                .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtDniEliminar.setEditable(false);
        txtNombreEliminar.setEditable(false);
        txtTelefonoEliminar.setEditable(false);
        txtComprasTotalesEliminar.setEditable(false);

        jTabbedPane1.addTab("Eliminar Cliente", jPanel9);

        jLabel6.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MODIFICAR NOMBRE");

        jLabel8.setText("Seleccionar Codigo: ");

        jLabel9.setText("Nombre Actual");

        jLabel10.setText("Nuevo Nombre");

        btnModificarNombre.setText("Modificar Nombre");
        btnModificarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarNombreActionPerformed(evt);
            }
        });

        btnActualizarTabla.setText("Actualizar Tabla");
        btnActualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTablaActionPerformed(evt);
            }
        });

        listCodigoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCodigoClienteActionPerformed(evt);
            }
        });

        txtNombreActual.setEditable(false);

        tablaClienteNombres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaClienteNombres);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel7);

        btnCargarUploadListaIDModNomCliente.setText("Cargar/Actualizar Lista de Codigo de Cliente");
        btnCargarUploadListaIDModNomCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarUploadListaIDModNomClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCargarUploadListaIDModNomCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreActual, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(58, 58, 58)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(btnActualizarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnActualizarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnCargarUploadListaIDModNomCliente)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNuevoNombre))
                        .addGap(32, 32, 32)
                        .addComponent(btnModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("MODIFICAR NOMBRE", jPanel5);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegresar)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCodigoActionPerformed
        // TODO add your handling code here:
        String codigoGenrerado = clienteVectores.correlativo();
        txtCodeGenrerado.setText(codigoGenrerado);
    }//GEN-LAST:event_btnGenerarCodigoActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        try
        {
            if(txtCodeGenrerado.getText().equals("") || txtTelefono.getText().equals(null)
                || txtNombre.getText().equals("") || txtDNI.getText().equals(null))
            {
                JOptionPane.showMessageDialog(null,"Lllene todos los campos");
            }
            else
            {
                String codigoCliente    = txtCodeGenrerado.getText();
                String telefono         = txtTelefono.getText();
                String nombre           = txtNombre.getText();
                String dni              = txtDNI.getText();

                Cliente objetoCliente = new Cliente(codigoCliente, dni, nombre, telefono);
                clienteVectores.agregarCliente(objetoCliente);
                clienteVectores.grabarEnArchivo(objetoCliente);
                
                JOptionPane.showMessageDialog(null,"Cliente agregado correctamente!!");
            }
            
        }
        catch(Exception e)
        {
            System.out.println("Excepcion en btnAgregarCliente: " + e);
        }
        
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void mostratTablaCLientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostratTablaCLientesActionPerformed
        // TODO add your handling code here:
        modeloDeTabla.setRowCount(0);
        cargarDatosTablaClientes();
    }//GEN-LAST:event_mostratTablaCLientesActionPerformed

    private void listCodTelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCodTelClienteActionPerformed
        // TODO add your handling code here:
        try
        {
            String codigoSeleccionado = listCodTelCliente.getSelectedItem().toString();
            String telefonoSelecionado = clienteVectores.buscarcodigoGetTelefono(codigoSeleccionado);
            txtTelActual.setText(telefonoSelecionado);
        }
        catch(Exception e)
        {
            System.out.println("Excepcion en cboBoxCodigo-TelefonoCliente: " + e);
        }
        
    }//GEN-LAST:event_listCodTelClienteActionPerformed

    private void listCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCodigoClienteActionPerformed
        // TODO add your handling code here:
        try
        {
            String codigoSeleccionado = listCodigoCliente.getSelectedItem().toString();
            String telefonoSelecionado = clienteVectores.buscarcodigoGetNombre(codigoSeleccionado);
            txtNombreActual.setText(telefonoSelecionado);
        }
        catch(Exception e)
        {
            System.out.println("Excepcion en cboBoxCodigo-CodigoCliente: " + e);
        }
    }//GEN-LAST:event_listCodigoClienteActionPerformed

    private void btnModificarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarTelefonoActionPerformed
        // TODO add your handling code here:
        try
        {
            if(txtNuevoTel.getText().equals("") || txtTelActual.getText().equals(""))
            {
                 JOptionPane.showMessageDialog(null, "Rellenes los campos");
            }
            else
            {
                String codigoSeleccionad = listCodigoCliente.getSelectedItem().toString();
                String nuevoTelefono     = txtNuevoTel.getText();

                Cliente objClientModificar =  clienteVectores.buscarcodigo(codigoSeleccionad);

                boolean estadoModify = clienteVectores.modificarTELEFONO(objClientModificar, nuevoTelefono);
                if(estadoModify == true)
                {
                    clienteVectores.grabarModificareliminar();
                    JOptionPane.showMessageDialog(null, "Dato Telefono modificado exitosamente");
                }
                else
                {
                    String msgExcept = "Ocurrio algo inesperado al intentar modificar el telefono";
                    JOptionPane.showMessageDialog(null,msgExcept);
                    System.out.println(msgExcept);
                }
            }
        }
        catch(Exception e)
        {
            System.out.println("Excepcion en btnModificarTelefono: " + e);
        }
        
    }//GEN-LAST:event_btnModificarTelefonoActionPerformed

    private void tablaClienteTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaClienteTelefonoActionPerformed
        // TODO add your handling code here:
        modeloDeTablaTel.setRowCount(0);
        cargarDatosTablaClientes();
    }//GEN-LAST:event_tablaClienteTelefonoActionPerformed

    private void btnActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTablaActionPerformed
        // TODO add your handling code here:
        modeloDeTablaNombre.setRowCount(0);
        cargarDatosTablaClientes();
    }//GEN-LAST:event_btnActualizarTablaActionPerformed

    private void btnModificarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarNombreActionPerformed
        // TODO add your handling code here:
        try
        {
            if(txtNuevoNombre.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Rellenes los campos");
            }
            else
            {
                String codigoSeleccionad = listCodigoCliente.getSelectedItem().toString();
                String nuevoNobre        = txtNuevoNombre.getText();

                Cliente objClientModificar =  clienteVectores.buscarcodigo(codigoSeleccionad);

                boolean estadoModify = clienteVectores.modificarNombreCliente(objClientModificar, nuevoNobre);
                if(estadoModify == true)
                {
                    clienteVectores.grabarModificareliminar();
                    JOptionPane.showMessageDialog(null, "Dato Nombre modificado exitosamente");
                }
                else
                {
                    String msgExcept = "Ocurrio algo inesperado al intentar modificar el nombre";
                    JOptionPane.showMessageDialog(null,msgExcept);
                    System.out.println(msgExcept);
                }
            }
        }
        catch(Exception e)
        {
            System.out.println("Excepcion en btnModificarNombre: " + e);
        }
        
    }//GEN-LAST:event_btnModificarNombreActionPerformed

    public void cargarListaIDClientElimianr()
    {
        cboBoxIDEliminar.removeAllItems(); // eliminar los item default
        
        ArrayList<String> listaCodClienteEliminar = objAyuda.cargarCodigosClientes();
        
        // cargando los datos de la lista proveedores al combo box
        for (int i = 0; i < listaCodClienteEliminar.size(); i++)
        {
            String codClienteEliminar = listaCodClienteEliminar.get(i);
            cboBoxIDEliminar.addItem(codClienteEliminar);            
        }
        
        cboBoxIDEliminar.setSelectedIndex(0);
        cboBoxIDEliminar.setSelectedItem(0);
    }
    
    private void btnCargarUploadListaIDEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarUploadListaIDEliminarClienteActionPerformed
        // TODO add your handling code here:
        cargarListaIDClientElimianr();
    }//GEN-LAST:event_btnCargarUploadListaIDEliminarClienteActionPerformed

    private void cboBoxIDEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBoxIDEliminarActionPerformed
        // TODO add your handling code here:
        try
        {
            String codSeleccionado = cboBoxIDEliminar.getSelectedItem().toString();
            Cliente objElminarCliente = clienteVectores.buscarcodigo(codSeleccionado);
            
            String DNI              = objElminarCliente.getDNI();
            String nombre           = objElminarCliente.getNombre();
            String telefono         = objElminarCliente.getTelefono();
            String crompasTotales   = Integer.toString(objElminarCliente.getComprasTotales());
            
            txtDniEliminar.setText(DNI);
            txtNombreEliminar.setText(nombre);
            txtTelefonoEliminar.setText(telefono);
            txtComprasTotalesEliminar.setText(crompasTotales);
            
        }
        catch(Exception e)
        {
            System.out.println("Ocurrio una excepcion en cboBoxIDEliminar: " + e);
        }
    }//GEN-LAST:event_cboBoxIDEliminarActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // TODO add your handling code here:
        try
        {
            int confirmed = JOptionPane.showConfirmDialog(null, 
            "¿Esta seguro de elimnar este cliente?", "Mensaje de Avertencia",
           JOptionPane.YES_NO_OPTION);

            if (confirmed == JOptionPane.YES_OPTION)
            {
                String codigoSeleccionado   = cboBoxIDEliminar.getSelectedItem().toString();
                Cliente objEliminarCliente = clienteVectores.buscarcodigo(codigoSeleccionado);
                if ( objEliminarCliente.getCodigoCliente().equals("Error"))
                {
                    JOptionPane.showMessageDialog(null, "No se encontro el codigo");
                }
                else
                {
                    clienteVectores.eliminar(objEliminarCliente);
                    clienteVectores.grabarModificareliminar();
                    JOptionPane.showMessageDialog(null, "Cliente eliminado satisfactoriamente");
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Operacion cancelada");
            }
        }
        catch(Exception e)
        {
            System.out.println("Ocurrio una excepcion en btnEleiminar: " + e);
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed
    
    private void btnCargarUploadListaIDModTelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarUploadListaIDModTelClienteActionPerformed
        // TODO add your handling code here:
        cargarItemsListaCodigo();
    }//GEN-LAST:event_btnCargarUploadListaIDModTelClienteActionPerformed

    private void btnCargarUploadListaIDModNomClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarUploadListaIDModNomClienteActionPerformed
        // TODO add your handling code here:
        cargarItemsListaCodigo();
    }//GEN-LAST:event_btnCargarUploadListaIDModNomClienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        if ( rol.equals("admin"))
        {
            MenuAdministrador jf1 = new MenuAdministrador("admin");
            jf1.show();

            dispose();
        }
        if( rol.equals("vendedor"))
        {
            MenuVendedor jf1 = new MenuVendedor("vendedor");
            jf1.show();

            dispose();
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void cargarItemsListaCodigo()
    {
        ArrayList<String> listaProductos = objAyuda.cargarCodigosClientes();
        
        listCodTelCliente.removeAllItems();
        listCodigoCliente.removeAllItems();
               
        for (int i =0; i <listaProductos.size(); i++)
        {
            listCodTelCliente.addItem(listaProductos.get(i));
            listCodigoCliente.addItem(listaProductos.get(i));
        }
        
        listCodTelCliente.setSelectedItem(0);
        listCodigoCliente.setSelectedItem(0);
    }
    
    public void cargarDatosTablaClientes()
    {
        modeloDeTabla.setRowCount(0);
        modeloDeTablaTel.setRowCount(0);
        modeloDeTablaNombre.setRowCount(0);
        // creacion de arreglo para guardar los datos y subirlos a la tabla
        String datosMostrar[]           = new String[5];
        String datosMostrarTelefono[]   = new String[2];
        String datosMostrarNombre[]     = new String[2];
        // datos
        String partesLocal[] = null;
        //objAyuda.crearArchivoSEGUNDAFORMA("ListaClientes.csv");
        try
        {
            String lineaLocal;
            FileReader     fr     = new FileReader("ListaClientes.csv");
            BufferedReader lector = new BufferedReader(fr); // el lector ya tiene el archivo
            // imprimiendo el archivo
            while( (lineaLocal = lector.readLine()) != null) 
            // obten la primera linea del archivo, y si la linea no hay nada,entonces termina
            {
                partesLocal = lineaLocal.split(","); // hasta que encuentra coma cambia de parte
                for (int i=0; i < partesLocal.length; i++)
                {
                    datosMostrar[0] = partesLocal[0]; // codigo
                    datosMostrar[1] = partesLocal[1]; // dni
                    datosMostrar[2] = partesLocal[2]; // nombre
                    datosMostrar[3] = partesLocal[3]; // telefono
                    datosMostrar[4] = partesLocal[4]; // compras totales
                    
                    //  datos Telefono
                    datosMostrarTelefono[0] = partesLocal[0]; // codigo
                    datosMostrarTelefono[1] = partesLocal[3]; // telefono
                    
                    //  datos nombre
                    datosMostrarNombre[0] = partesLocal[0]; // codigo
                    datosMostrarNombre[1] = partesLocal[2]; // telefono
                }
                modeloDeTabla.addRow(datosMostrar);
                modeloDeTablaTel.addRow(datosMostrarTelefono);
                modeloDeTablaNombre.addRow(datosMostrarNombre);
            }
            lector.close();
            fr.close();
        }
        catch(Exception e) // lanzar un mensaje en caso de que suceda un error
        {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error de tipo: " + e);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente_Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTabla;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnCargarUploadListaIDEliminarCliente;
    private javax.swing.JButton btnCargarUploadListaIDModNomCliente;
    private javax.swing.JButton btnCargarUploadListaIDModTelCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnGenerarCodigo;
    private javax.swing.JButton btnModificarNombre;
    private javax.swing.JButton btnModificarTelefono;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboBoxIDEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> listCodTelCliente;
    private javax.swing.JComboBox<String> listCodigoCliente;
    private javax.swing.JButton mostratTablaCLientes;
    private javax.swing.JTable tablaClienteNombres;
    private javax.swing.JButton tablaClienteTelefono;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaTelCliente;
    private javax.swing.JTextField txtCodeGenrerado;
    private javax.swing.JTextField txtComprasTotalesEliminar;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDniEliminar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreActual;
    private javax.swing.JTextField txtNombreEliminar;
    private javax.swing.JTextField txtNuevoNombre;
    private javax.swing.JTextField txtNuevoTel;
    private javax.swing.JTextField txtTelActual;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoEliminar;
    // End of variables declaration//GEN-END:variables
}
